#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t gummy"

$L "____ _    _ _  _ _  _ _   _";
$L "| __  |  |  |\\/| |\\/|  \\_/";
$L "|__]  |__|  |  | |  |   |";
$L "Welcome to Android `getprop ro.build.version.release` / Gummy-`getprop ro.tg.version`";
